# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nudge < Formula
  desc "Get a text when your script finishes. CLI companion for nudge.sh."
  homepage "https://nudge.sh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dotsquare-Labs/nudge-cli/releases/download/v0.1.0/nudge_darwin_amd64.tar.gz"
      sha256 "caa9cc5e40c67504095b88e371dcfb8301abf4d045f23076d21c1c2d8431c5e1"

      define_method(:install) do
        bin.install "nudge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dotsquare-Labs/nudge-cli/releases/download/v0.1.0/nudge_darwin_arm64.tar.gz"
      sha256 "cb07266878d838e0685ae52b9491a8c4dfe5834022fd838d611a921bc5d9aeb6"

      define_method(:install) do
        bin.install "nudge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dotsquare-Labs/nudge-cli/releases/download/v0.1.0/nudge_linux_amd64.tar.gz"
      sha256 "a4d9b1892e9ea813c1f4dab9ff45589a647d652f5e91cc82f05fb6f4b42c0e18"
      define_method(:install) do
        bin.install "nudge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dotsquare-Labs/nudge-cli/releases/download/v0.1.0/nudge_linux_arm64.tar.gz"
      sha256 "6548c85bfd9d9c2552fa187e15e6ad42e747bdc1e8b201b0a087997664b722f5"
      define_method(:install) do
        bin.install "nudge"
      end
    end
  end

  test do
    assert_match "nudge", shell_output("#{bin}/nudge --version")
  end
end
